server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        # Принудительно обрабатывать preflight запросы OPTIONS на уровне шлюза
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173" # Для локальной разработки Vue
              - "http://localhost:3000" # Для работы Vue внутри Docker
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        # Публичный маршрут склада (только для просмотра GET)
        - id: inventory-service-public
          # lb:// - Load Balancer. Шлюз запросит у Eureka адрес сервиса с именем inventory-service
          uri: lb://inventory-service
          # Все запросы, начинающиеся с /api/inventory/, будут перенаправлены туда
          predicates:
            - Path=/api/inventory/**
            - Method=GET # GET запросы всем без авторизации

        - id: inventory-service-admin
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
            - Method=POST,PUT,DELETE,OPTIONS
          filters:
            - AuthenticationFilter=OWNER

        # Маршрут для order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        # Маршрут корзины
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter

        # Публичный маршрут на регистрацию и вход
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/user/login, /api/user/register

        # Защищенный маршрут на баланс и пополнение
        - id: user-service-protected
          uri: lb://user-service
          predicates:
            - Path=/api/user/balance, /api/user/recharge, /api/user/me
          filters:
            - AuthenticationFilter

        # Админский маршрут пользователей (список пользователей, смена ролей доступна только админу)
        - id: user-service-admin-panel
          uri: lb://user-service
          predicates:
            - Path=/api/user/all, /api/user/*/role
          filters:
            - AuthenticationFilter=ADMIN

        # Удаление пользователей для админа
        - id: user-service-delete-admin
          uri: lb://user-service
          predicates:
            - Path=/api/user/*
            - Method=DELETE,OPTIONS
          filters:
            - AuthenticationFilter=ADMIN

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

app:
  jwt:
    secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}