server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173" # Для локальной разработки Vue
              - "http://localhost:3000" # Для работы Vue внутри Docker
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers: "*"
      routes:
        # Маршрут для inventory-service
        - id: inventory-service
          # lb:// - Load Balancer. Шлюз запросит у Eureka адрес сервиса с именем inventory-service
          uri: lb://inventory-service
          # Все запросы, начинающиеся с /api/inventory/, будут перенаправлены туда
          predicates:
            - Path=/api/inventory/**

        # Маршрут для order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - AuthenticationFilter

        # Маршрут для пользователей
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        # Маршрут корзины
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

app:
  jwt:
    secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}