server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost
  client:
    # Указываем серверу Eureka не регистрировать самого себя в своем же списке
    register-with-eureka: false
    fetch-registry: false